"""empty message

Revision ID: 0a83c9b94a82
Revises: 5ba2647b5e72
Create Date: 2022-03-04 14:57:24.818306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a83c9b94a82'
down_revision = '5ba2647b5e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('completion_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'completion_time')
    op.drop_column('notifications', 'start_time')
    # ### end Alembic commands ###
