"""empty message

Revision ID: 218eee006a39
Revises: 9c6a4e7a8b51
Create Date: 2022-02-03 21:21:22.417114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218eee006a39'
down_revision = '9c6a4e7a8b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isParent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isParent')
    # ### end Alembic commands ###
