"""empty message

Revision ID: 365088422a36
Revises: 3a9fbfba03f9
Create Date: 2022-02-09 23:04:50.757923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365088422a36'
down_revision = '3a9fbfba03f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_caregiver_groups', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_caregiver_groups', 'parent_id')
    # ### end Alembic commands ###
