"""empty message

Revision ID: 3acadeccccf6
Revises: 5ec5633e79b3
Create Date: 2022-02-09 23:27:15.919930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acadeccccf6'
down_revision = '5ec5633e79b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parent_caregiver_groups')
    op.drop_table('parent_caregivee_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_caregivee_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('caregivee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caregivee_id'], ['users.id'], name='parent_caregivee_groups_caregivee_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='parent_caregivee_groups_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='parent_caregivee_groups_pkey')
    )
    op.create_table('parent_caregiver_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='parent_caregiver_groups_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='parent_caregiver_groups_pkey')
    )
    op.drop_table('groups')
    # ### end Alembic commands ###
