"""empty message

Revision ID: 3fc1165f6a09
Revises: 5befb387cb2f
Create Date: 2022-02-14 23:42:29.976445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc1165f6a09'
down_revision = '5befb387cb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiverrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_from', sa.Integer(), nullable=True),
    sa.Column('uid_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uid_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caregiverrequests')
    # ### end Alembic commands ###
