"""empty message

Revision ID: 4a8970da8581
Revises: b37f95da8778
Create Date: 2022-01-15 19:45:02.526527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8970da8581'
down_revision = 'b37f95da8778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
