"""empty message

Revision ID: 58507c09640b
Revises: 3e1796fbe382
Create Date: 2022-02-28 21:50:28.378027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58507c09640b'
down_revision = '3e1796fbe382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('repeated_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('locations', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('locations', 'location_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('location_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'name')
    op.drop_table('notifications')
    # ### end Alembic commands ###
