"""empty message

Revision ID: 5ba2647b5e72
Revises: d684aeab466e
Create Date: 2022-03-04 00:01:16.769870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ba2647b5e72'
down_revision = 'd684aeab466e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status = postgresql.ENUM('NOT_STARTED', 'STARTED', 'COMPLETED', 'LATE', name='notificationstatus')
    status.create(op.get_bind())
    op.add_column('notifications', sa.Column('status', sa.Enum('NOT_STARTED', 'STARTED', 'COMPLETED', 'LATE', name='notificationstatus'), nullable=True))
    op.add_column('notifications', sa.Column('sent_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['sent_to'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'sent_to')
    op.drop_column('notifications', 'status')
    status = postgresql.ENUM('NOT_STARTED', 'STARTED', 'COMPLETED', 'LATE', name='notificationstatus')
    status.drop(op.get_bind())
    # ### end Alembic commands ###
