"""empty message

Revision ID: 5ec5633e79b3
Revises: 365088422a36
Create Date: 2022-02-09 23:08:23.353594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec5633e79b3'
down_revision = '365088422a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'parent_caregiver_groups', 'users', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_caregiver_groups', type_='foreignkey')
    # ### end Alembic commands ###
