"""empty message

Revision ID: 757a2e0e420b
Revises: 
Create Date: 2022-01-09 16:41:46.638058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757a2e0e420b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True, is_unique=False),
    sa.Column('caregiver', sa.Boolean(), nullable=True, is_unique=False),
    sa.Column('parent', sa.Boolean(), nullable=True, is_unique=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
