"""empty message

Revision ID: 9710766fd1b6
Revises: 218eee006a39
Create Date: 2022-02-03 21:27:58.561016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9710766fd1b6'
down_revision = '218eee006a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent', sa.Boolean(), nullable=True))
    op.drop_column('users', 'isParent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isParent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'parent')
    # ### end Alembic commands ###
