"""empty message

Revision ID: 9c6a4e7a8b51
Revises: 3a2c8a0c9d92
Create Date: 2022-02-03 20:28:08.629226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6a4e7a8b51'
down_revision = '3a2c8a0c9d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'locations', ['location_id'], ['id'])
    op.drop_column('tasks', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
