"""empty message

Revision ID: a4176b3a5226
Revises: 73a4685201c5
Create Date: 2022-01-31 00:33:31.853468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4176b3a5226'
down_revision = '73a4685201c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('caregiver_notes', sa.String(), nullable=True))
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'caregiver_notes')
    # ### end Alembic commands ###
