"""empty message

Revision ID: b37f95da8778
Revises: 5791cc1a3701
Create Date: 2022-01-15 19:43:08.273377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37f95da8778'
down_revision = '5791cc1a3701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
