"""empty message

Revision ID: c30f31532d5c
Revises: 0a83c9b94a82
Create Date: 2022-05-01 19:42:53.757429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30f31532d5c'
down_revision = '0a83c9b94a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_task_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_task_id_fkey', 'notifications', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
